name: Release to Store
on:
  workflow_dispatch:

jobs:
  release:
    runs-on: runs-on=${{ github.run_id }}/runner=sw-amd64
    steps:
    - uses: shopware/github-actions/store-release@main   
      with:
        extensionName: ${{ github.event.repository.name }}
        accountUser: ${{ secrets.SHOPWARE_ACCOUNT_USER }}
        accountPassword: ${{ secrets.SHOPWARE_ACCOUNT_PASSWORD }}
        ghToken: ${{ secrets.GITHUB_TOKEN }}